import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import NavbarDashboard from "@/components/common/navbarDashboard";
import SideBar from "@/components/common/sideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <>
          <div className="flex overflow-hidden h-screen">
            {/* Sidebar */}
            <aside className="w-1/6 min-w-[220px] h-full overflow-y-auto border-r bg-gray-50">
              <SideBar />
            </aside>

            {/* Main section */}
            <main className="flex flex-col flex-1">
              {/* Navbar (fixed at top of main section) */}
              <NavbarDashboard />

              {/* Scrollable page content */}
              <div className="flex-1 ">
                {children}
              </div>
            </main>
          </div>
        </>
      </body>
    </html>
  );
}
